FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY pom.xml .
COPY core/pom.xml core/
COPY games/pom.xml games/
COPY infrastructure/pom.xml infrastructure/

RUN apk add --no-cache maven

COPY . .

RUN mvn clean package -DskipTests

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "infrastructure/api/target/api-1.0.0-SNAPSHOT.jar"]